version: '3.8'
services:
  mysql:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqlconfig:/etc/mysql/conf.d
      # - ./init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:${DATABASE_PORT}'
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    command: >
      sh -c "yarn && yarn migration:run && yarn seed:run && yarn start:dev"
    depends_on:
      - mysql
    volumes:
      - .:/app/
      - /app/node_modules
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - 80:80
    depends_on:
      - mysql
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      SERVICES: s3,ses,sqs,buckets,kinesis
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d

volumes:
  mysqldata: {}
