version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      SERVICES: s3,ses,sqs,buckets,kinesis
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d