version: '3.8'
services:
  mssql:
    container_name: sql-server-db
    image: topaztechnology/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA:"Y"
      - SQL_USER:${DATABASE_USERNAME}
      - SQL_PASSWORD:${DATABASE_PASSWORD}
      - SQL_DB:${DATABASE_NAME}
    volumes:
      - mssql-data:/var/opt/mssql
  api:
    container_name: 'api'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mysql
    volumes:
      - .:/app/
      - /app/node_modules
